"use client";

import { useEffect, useMemo, useState } from "react";
import {
  Activity,
  Clock,
  Database,
  FileClock,
  Filter,
  Loader2,
  RefreshCcw,
  Search,
  ShieldCheck,
  TerminalSquare,
  UserRound,
} from "lucide-react";
import { toast } from "sonner";

import { apiFetch } from "@/lib/api";
import { formatDateTime } from "@/lib/format";
import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type AuditLogItem = {
  id: string;
  actor: string;
  action: string;
  entity_type: string;
  entity_id: string | null;
  description: string | null;
  created_at: string;
};

type AuditLogsResponse = {
  total: number;
  limit: number;
  offset: number;
  items: AuditLogItem[];
};

const actionFilters = [
  "all",
  "login_user",
  "register_user",
  "create_transaction",
  "update_alert_status",
  "create_transaction_label",
  "seed_database",
] as const;

export default function AuditLogsPage() {
  const [logs, setLogs] = useState<AuditLogItem[]>([]);
  const [total, setTotal] = useState(0);
  const [search, setSearch] = useState("");
  const [actionFilter, setActionFilter] =
    useState<(typeof actionFilters)[number]>("all");
  const [loading, setLoading] = useState(true);

  async function loadLogs() {
    setLoading(true);

    try {
      const data = await apiFetch<AuditLogsResponse>("/audit-logs?limit=100");
      setLogs(data.items);
      setTotal(data.total);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to load audit logs");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadLogs();
  }, []);

  const filteredLogs = useMemo(() => {
    const keyword = search.trim().toLowerCase();

    return logs.filter((log) => {
      const matchesAction =
        actionFilter === "all" ? true : log.action === actionFilter;

      const matchesSearch = keyword
        ? [
            log.actor,
            log.action,
            log.entity_type,
            log.entity_id,
            log.description,
            log.created_at,
          ]
            .filter(Boolean)
            .some((item) => String(item).toLowerCase().includes(keyword))
        : true;

      return matchesAction && matchesSearch;
    });
  }, [logs, search, actionFilter]);

  const uniqueActors = new Set(logs.map((log) => log.actor)).size;
  const entityCount = new Set(logs.map((log) => `${log.entity_type}:${log.entity_id}`)).size;
  const latestLog = logs[0];

  return (
    <div className="space-y-8">
      <section className="flex flex-col justify-between gap-6 xl:flex-row xl:items-end">
        <div>
          <div className="mb-4 flex items-center gap-2">
            <Badge className="rounded-sm bg-cyan-400/10 text-cyan-300 hover:bg-cyan-400/10">
              AUDIT MONITOR
            </Badge>
            <span className="text-xs uppercase tracking-[0.14em] text-slate-600">
              / System Ledger / Immutable Activity Trail
            </span>
          </div>

          <h1 className="text-5xl font-black tracking-tight text-slate-100">
            AUDIT LOGS
          </h1>
          <p className="mt-3 max-w-3xl text-base leading-7 text-slate-400">
            Monitor operational events generated by authentication, fraud
            simulation, alert investigation, transaction labeling, and backend
            system activity.
          </p>
        </div>

        <Button
          onClick={loadLogs}
          className="rounded-sm bg-cyan-400 font-bold text-[#06111f] hover:bg-cyan-300"
        >
          <RefreshCcw className="mr-2 h-4 w-4" />
          Refresh Ledger
        </Button>
      </section>

      <section className="grid gap-6 md:grid-cols-4">
        <AuditMetric
          label="Total Events"
          value={total}
          icon={<TerminalSquare className="h-8 w-8 text-cyan-300" />}
        />
        <AuditMetric
          label="Visible Events"
          value={filteredLogs.length}
          icon={<Activity className="h-8 w-8 text-emerald-300" />}
        />
        <AuditMetric
          label="Actors"
          value={uniqueActors}
          icon={<UserRound className="h-8 w-8 text-blue-200" />}
        />
        <AuditMetric
          label="Entities"
          value={entityCount}
          icon={<Database className="h-8 w-8 text-red-200" />}
        />
      </section>

      <section className="grid gap-4 xl:grid-cols-[1fr_1.2fr]">
        <div className="trust-panel-soft rounded-md p-4">
          <p className="trust-label mb-3">Search Ledger</p>
          <div className="flex h-11 items-center gap-3 rounded-sm bg-[#050b18] px-3">
            <Search className="h-4 w-4 text-slate-500" />
            <Input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Actor / action / entity / description..."
              className="h-full border-0 bg-transparent px-0 text-slate-200 placeholder:text-slate-600 focus-visible:ring-0"
            />
          </div>
        </div>

        <div className="trust-panel-soft rounded-md p-4">
          <div className="mb-3 flex items-center justify-between">
            <p className="trust-label">Action Filter</p>
            <Filter className="h-4 w-4 text-slate-500" />
          </div>

          <div className="flex flex-wrap gap-2">
            {actionFilters.map((action) => (
              <button
                key={action}
                onClick={() => setActionFilter(action)}
                className={cn(
                  "rounded-sm border px-3 py-2 text-xs font-bold uppercase tracking-[0.1em]",
                  actionFilter === action
                    ? "border-cyan-300 bg-cyan-400/10 text-cyan-300"
                    : "border-white/10 bg-[#050b18] text-slate-500 hover:text-slate-300"
                )}
              >
                {action.replaceAll("_", " ")}
              </button>
            ))}
          </div>
        </div>
      </section>

      <section className="grid gap-8 xl:grid-cols-[1fr_360px]">
        <Card className="trust-panel overflow-hidden rounded-md border-cyan-300/10 text-slate-100">
          <CardContent className="p-0">
            <div className="flex items-center justify-between border-b border-white/10 bg-white/[0.04] px-6 py-4">
              <div>
                <h2 className="font-bold uppercase tracking-[0.12em] text-slate-200">
                  Activity Ledger
                </h2>
                <p className="mt-1 text-sm text-slate-500">
                  Ordered by newest system event.
                </p>
              </div>
              <FileClock className="h-5 w-5 text-cyan-300" />
            </div>

            {loading ? (
              <div className="flex h-80 items-center justify-center text-slate-400">
                <Loader2 className="mr-2 h-5 w-5 animate-spin text-cyan-300" />
                Loading audit ledger...
              </div>
            ) : filteredLogs.length === 0 ? (
              <div className="p-10 text-center text-slate-500">
                No audit event matched your filter.
              </div>
            ) : (
              <div className="divide-y divide-white/5">
                {filteredLogs.map((log) => (
                  <AuditRow key={log.id} log={log} />
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        <div className="space-y-6">
          <Card className="trust-panel rounded-md border-cyan-300/10 text-slate-100">
            <CardContent className="p-6">
              <p className="trust-label">Latest Event</p>

              {!latestLog ? (
                <p className="mt-5 text-sm text-slate-500">No event available.</p>
              ) : (
                <div className="mt-5 space-y-3">
                  <InfoBox label="Actor" value={latestLog.actor} />
                  <InfoBox label="Action" value={latestLog.action} />
                  <InfoBox label="Entity" value={latestLog.entity_type} />
                  <InfoBox
                    label="Timestamp"
                    value={formatDateTime(latestLog.created_at)}
                  />
                </div>
              )}
            </CardContent>
          </Card>

          <Card className="trust-panel rounded-md border-cyan-300/10 text-slate-100">
            <CardContent className="p-6">
              <div className="flex items-start justify-between">
                <div>
                  <p className="trust-label">Ledger Integrity</p>
                  <h3 className="mt-3 text-2xl font-black text-slate-100">
                    Verified
                  </h3>
                </div>
                <ShieldCheck className="h-8 w-8 text-emerald-300" />
              </div>

              <div className="mt-6 space-y-3">
                <ProtocolRow label="Storage" value="PostgreSQL" />
                <ProtocolRow label="Mode" value="Append-only demo" />
                <ProtocolRow label="Status" value="Active" active />
                <ProtocolRow label="Coverage" value="Auth / Alerts / Labels" />
              </div>
            </CardContent>
          </Card>

          <Card className="trust-panel rounded-md border-cyan-300/10 text-slate-100">
            <CardContent className="p-6">
              <p className="trust-label">Action Distribution</p>
              <div className="mt-6 space-y-4">
                {getActionDistribution(logs).map((item) => (
                  <DistributionRow
                    key={item.action}
                    action={item.action}
                    count={item.count}
                    total={logs.length}
                  />
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </section>
    </div>
  );
}

function AuditMetric({
  label,
  value,
  icon,
}: {
  label: string;
  value: number;
  icon: React.ReactNode;
}) {
  return (
    <Card className="trust-panel rounded-xl border-cyan-300/10 text-slate-100">
      <CardContent className="p-6">
        <div className="flex items-start justify-between">
          <div>
            <p className="trust-label">{label}</p>
            <p className="mt-4 text-4xl font-black text-cyan-300">{value}</p>
          </div>
          {icon}
        </div>
      </CardContent>
    </Card>
  );
}

function AuditRow({ log }: { log: AuditLogItem }) {
  return (
    <div className="p-6 transition hover:bg-cyan-400/[0.03]">
      <div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between">
        <div className="flex gap-4">
          <div className="mt-1 flex h-11 w-11 shrink-0 items-center justify-center rounded-md border border-cyan-300/10 bg-cyan-400/10 text-cyan-300">
            <TerminalSquare className="h-5 w-5" />
          </div>

          <div>
            <div className="flex flex-wrap items-center gap-3">
              <span className="rounded-sm border border-cyan-300/20 bg-cyan-400/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.1em] text-cyan-300">
                {log.action.replaceAll("_", " ")}
              </span>
              <span className="trust-mono text-xs text-slate-600">
                {formatDateTime(log.created_at)}
              </span>
            </div>

            <p className="mt-3 text-sm leading-6 text-slate-300">
              {log.description || "System event recorded."}
            </p>

            <div className="mt-4 flex flex-wrap gap-3 text-xs text-slate-500">
              <span>
                Actor: <span className="text-slate-300">{log.actor}</span>
              </span>
              <span>
                Entity:{" "}
                <span className="text-slate-300">{log.entity_type}</span>
              </span>
              {log.entity_id && (
                <span className="trust-mono">
                  ID: <span className="text-slate-300">{log.entity_id}</span>
                </span>
              )}
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2 text-xs uppercase tracking-[0.1em] text-emerald-300">
          <Clock className="h-4 w-4" />
          Logged
        </div>
      </div>
    </div>
  );
}

function InfoBox({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div className="rounded-sm border border-white/10 bg-[#050b18] p-3">
      <p className="trust-label">{label}</p>
      <p className="mt-2 break-words text-sm text-slate-200">{value}</p>
    </div>
  );
}

function ProtocolRow({
  label,
  value,
  active,
}: {
  label: string;
  value: string;
  active?: boolean;
}) {
  return (
    <div className="flex items-center justify-between rounded-sm border border-white/10 bg-[#050b18] px-4 py-3">
      <span className="text-sm text-slate-400">{label}</span>
      <span className={cn("trust-mono text-sm", active ? "text-emerald-300" : "text-slate-500")}>
        {value}
      </span>
    </div>
  );
}

function DistributionRow({
  action,
  count,
  total,
}: {
  action: string;
  count: number;
  total: number;
}) {
  const percent = total > 0 ? Math.round((count / total) * 100) : 0;

  return (
    <div>
      <div className="mb-2 flex items-center justify-between text-sm">
        <span className="truncate text-slate-400">
          {action.replaceAll("_", " ")}
        </span>
        <span className="trust-mono text-slate-500">{count}</span>
      </div>
      <div className="h-2 rounded-full bg-[#050b18]">
        <div
          className="h-full rounded-full bg-cyan-300"
          style={{ width: `${percent}%` }}
        />
      </div>
    </div>
  );
}

function getActionDistribution(logs: AuditLogItem[]) {
  const map = new Map<string, number>();

  for (const log of logs) {
    map.set(log.action, (map.get(log.action) || 0) + 1);
  }

  return Array.from(map.entries())
    .map(([action, count]) => ({ action, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 6);
}
