"use client";

import { useEffect, useState } from "react";
import {
    AlertOctagon,
    BarChart3,
    DatabaseZap,
    Loader2,
    MoreVertical,
    ShieldCheck,
    ShieldOff,
    Zap,
} from "lucide-react";

import { apiFetch } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";

type DashboardSummary = {
    total_transactions: number;
    total_accounts: number;
    total_devices: number;
    total_merchants: number;
    total_alerts: number;
    open_alerts: number;
    high_risk_transactions: number;
    blocked_transactions: number;
    average_fraud_score: number;
    risk_distribution: {
        low: number;
        medium: number;
        high: number;
    };
    status_distribution: {
        approved: number;
        flagged: number;
        blocked: number;
        pending: number;
    };
};

export default function DashboardPage() {
    const [summary, setSummary] = useState<DashboardSummary | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        apiFetch<DashboardSummary>("/dashboard/summary")
            .then(setSummary)
            .finally(() => setLoading(false));
    }, []);

    if (loading) {
        return (
            <div className="flex min-h-[70vh] items-center justify-center text-slate-400">
                <Loader2 className="mr-2 h-5 w-5 animate-spin text-cyan-300" />
                Initializing Sentinel Core...
            </div>
        );
    }

    if (!summary) {
        return (
            <div className="trust-panel rounded-xl p-6 text-red-200">
                Failed to load dashboard summary. Make sure FastAPI backend is running.
            </div>
        );
    }

    return (
        <div className="space-y-8">
            <section>
                <div className="mb-4 flex items-center gap-2">
                    <Badge className="rounded-sm bg-cyan-400/10 text-cyan-300 hover:bg-cyan-400/10">
                        REAL-TIME STREAM
                    </Badge>
                    <span className="text-xs uppercase tracking-[0.22em] text-slate-600">
                        / Ledger / Mainnet_01
                    </span>
                </div>

                <h1 className="text-5xl font-black tracking-tight text-slate-100">
                    DASHBOARD
                </h1>
                <p className="mt-3 max-w-3xl text-base leading-7 text-slate-400">
                    Centralized threat monitoring for transaction fraud signals, high-risk
                    alerts, cross-border anomalies, and analyst validation workflows.
                </p>
            </section>

            <section className="grid gap-6 lg:grid-cols-3">
                <MetricCard
                    label="Global Risk Score"
                    value={summary.average_fraud_score.toFixed(2)}
                    icon={<ShieldOff className="h-9 w-9 text-slate-700" />}
                    footer="System Status: Nominal"
                    accent="cyan"
                />
                <MetricCard
                    label="Live Transactions"
                    value={summary.total_transactions.toLocaleString()}
                    icon={<BarChart3 className="h-9 w-9 text-slate-700" />}
                    footer="Synced from fraud engine"
                    accent="blue"
                />
                <MetricCard
                    label="Active Alerts"
                    value={String(summary.open_alerts).padStart(2, "0")}
                    icon={<AlertOctagon className="h-9 w-9 text-red-300" />}
                    footer={`${summary.high_risk_transactions} high-risk vectors detected`}
                    accent="red"
                />
            </section>

            <section className="grid gap-8 xl:grid-cols-[1fr_330px]">
                <Card className="trust-panel rounded-xl border-cyan-300/10 text-slate-100">
                    <CardContent className="p-0">
                        <div className="flex items-center justify-between border-b border-white/10 px-6 py-4">
                            <div>
                                <h2 className="text-xl font-bold">Live Activity Stream</h2>
                                <p className="mt-1 text-sm text-slate-500">
                                    Fraud events and security decisions generated by TrustLens.
                                </p>
                            </div>
                            <div className="flex gap-4 text-xs uppercase tracking-[0.16em] text-slate-500">
                                <span className="flex items-center gap-2">
                                    <span className="h-2 w-2 rounded-full bg-emerald-400" />
                                    Safe
                                </span>
                                <span className="flex items-center gap-2">
                                    <span className="h-2 w-2 rounded-full bg-red-300" />
                                    Critical
                                </span>
                            </div>
                        </div>

                        <div className="space-y-3 p-6">
                            <ActivityRow
                                variant="critical"
                                title="Unexpected Cross-Border Outflow"
                                badge="CRIMSON ALERT"
                                description={`${summary.high_risk_transactions} high-risk transactions require analyst review.`}
                                meta="REACTION REQUIRED"
                            />
                            <ActivityRow
                                variant="safe"
                                title="Handshake Successful"
                                badge="VERIFIED"
                                description={`${summary.status_distribution.approved} transactions approved by scoring engine.`}
                                meta="NODE: TRUSTLENS-AI"
                            />
                            <ActivityRow
                                variant="info"
                                title="Graph Sync Available"
                                badge="ROUTINE"
                                description="Transaction relations can be synchronized into Neo4j for graph exploration."
                                meta="GRAPH ENGINE READY"
                            />
                        </div>
                    </CardContent>
                </Card>

                <div className="space-y-6">
                    <Card className="trust-panel rounded-xl border-cyan-300/10 text-slate-100">
                        <CardContent className="p-6">
                            <div className="mb-6 flex items-center justify-between">
                                <h3 className="font-bold uppercase tracking-wide text-slate-300">
                                    Risk Distribution
                                </h3>
                                <DatabaseZap className="h-5 w-5 text-slate-500" />
                            </div>

                            <div className="space-y-5">
                                <RiskBar
                                    label="Low Risk"
                                    value={summary.risk_distribution.low}
                                    total={summary.total_transactions}
                                    tone="emerald"
                                />
                                <RiskBar
                                    label="Medium Risk"
                                    value={summary.risk_distribution.medium}
                                    total={summary.total_transactions}
                                    tone="cyan"
                                />
                                <RiskBar
                                    label="High Risk"
                                    value={summary.risk_distribution.high}
                                    total={summary.total_transactions}
                                    tone="red"
                                />
                            </div>
                        </CardContent>
                    </Card>

                    <Card className="trust-panel rounded-xl border-cyan-300/10 text-slate-100">
                        <CardContent className="p-6">
                            <h3 className="font-bold uppercase tracking-wide text-slate-300">
                                Node Status Map
                            </h3>

                            <div className="mt-8 flex h-44 items-center justify-center rounded-xl border border-cyan-300/10 bg-[#080f1f]">
                                <div className="flex h-20 w-20 items-center justify-center rounded-2xl border border-cyan-300/20 bg-cyan-400/10 text-cyan-300 trust-glow">
                                    <ShieldCheck className="h-9 w-9" />
                                </div>
                            </div>

                            <div className="mt-5 flex justify-between text-xs uppercase tracking-[0.16em] text-slate-500">
                                <span>Active Nodes: {summary.total_devices}</span>
                                <span>Offline: 0</span>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </section>
        </div>
    );
}

function MetricCard({
    label,
    value,
    icon,
    footer,
    accent,
}: {
    label: string;
    value: string;
    icon: React.ReactNode;
    footer: string;
    accent: "cyan" | "blue" | "red";
}) {
    const accentClass = {
        cyan: "text-cyan-300",
        blue: "text-blue-200",
        red: "text-red-200",
    }[accent];

    return (
        <Card className="trust-panel rounded-xl border-cyan-300/10 text-slate-100">
            <CardContent className="p-6">
                <div className="flex items-start justify-between">
                    <div>
                        <p className="trust-label">{label}</p>
                        <p className={`mt-4 text-4xl font-black ${accentClass}`}>{value}</p>
                    </div>
                    {icon}
                </div>
                <div className="mt-5 h-1 rounded-full bg-slate-800">
                    <div className="h-full w-2/3 rounded-full bg-cyan-300" />
                </div>
                <p className="mt-3 text-xs text-slate-500">{footer}</p>
            </CardContent>
        </Card>
    );
}

function ActivityRow({
    variant,
    title,
    badge,
    description,
    meta,
}: {
    variant: "critical" | "safe" | "info";
    title: string;
    badge: string;
    description: string;
    meta: string;
}) {
    const styles = {
        critical: "border-l-red-300 bg-red-400/5",
        safe: "border-l-emerald-400 bg-emerald-400/5",
        info: "border-l-cyan-300 bg-cyan-400/5",
    };

    return (
        <div className={`flex gap-4 border-l-4 p-4 ${styles[variant]}`}>
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-md bg-white/5">
                <Zap className="h-5 w-5 text-cyan-300" />
            </div>
            <div className="flex-1">
                <div className="flex flex-wrap items-center gap-3">
                    <h3 className="font-bold text-slate-100">{title}</h3>
                    <span className="rounded-sm bg-white/10 px-2 py-1 text-[10px] font-bold tracking-[0.14em] text-slate-300">
                        {badge}
                    </span>
                </div>
                <p className="mt-2 text-sm leading-6 text-slate-400">{description}</p>
                <p className="mt-2 text-[10px] uppercase tracking-[0.18em] text-slate-600">
                    {meta}
                </p>
            </div>
            <MoreVertical className="h-5 w-5 text-slate-600" />
        </div>
    );
}

function RiskBar({
    label,
    value,
    total,
    tone,
}: {
    label: string;
    value: number;
    total: number;
    tone: "emerald" | "cyan" | "red";
}) {
    const percent = total > 0 ? Math.round((value / total) * 100) : 0;
    const color = {
        emerald: "bg-emerald-400",
        cyan: "bg-cyan-300",
        red: "bg-red-300",
    }[tone];

    return (
        <div>
            <div className="mb-2 flex justify-between text-xs uppercase tracking-[0.14em]">
                <span className="text-slate-500">{label}</span>
                <span className="text-slate-300">{percent}%</span>
            </div>
            <div className="h-2 rounded-full bg-[#050b18]">
                <div className={`h-full rounded-full ${color}`} style={{ width: `${percent}%` }} />
            </div>
        </div>
    );
}